#!/usr/bin/with-contenv bash

IFS=" " read -r -a RUN_ARRAY <<< "$WEBROOT"

# set capabilities for domoticz binary
setcap cap_net_raw=+eip /usr/bin/domoticz

exec \
	s6-setuidgid abc /usr/bin/domoticz \
		-approot /usr/share/domoticz/ \
		-dbase /config/domoticz.db \
		-noupdate \
        -www 80 \
		-sslwww 443 \
		-sslcert /config/keys/server_cert.pem \
		-userdata /config/ \
		-webroot "${RUN_ARRAY[@]}"
